### ISSUE TITLE
Crafting is Broken in Bedrock

### ISSUE THREAD

**Issue by ibbotsoz** [elBukkit/MagicPlugin#788]
im a bedrock player on a java server. previous version worked well even for bedrock players. this version i am unable to craft the actual spell book/ wand, i put recipe in and can see the spell book there but i am unable to take and put in to my inventory.  i know it wont work as well as it does on java but it does imply that bedrock players would be able to use this.

**Comment by NathanWolf** [comment]
Guessing bedrock does not support custom item data in recipes. That is a shame. I have no real idea how to fix that without going back.

If you can, suggest to your server that they revert back to the old recipes using `/mconfig example set 7`

**Comment by NathanWolf** [comment]
I've been looking into this, and fortunately I _think_ it's only a problem with the current dev build. So nevermind what I said about the server reverting, I think it should be something I can fix pretty quickly.

**Comment by NathanWolf** [comment]
This is fixed in the current dev build- hopefully your server can update!

**Comment by ibbotsoz** [comment]
i have updated to the most recent magic release and still the same problem.  unable to craft most magical items when on bedrock. recipe works and shows the spell book in the end box but is unable to be moved into inventory.

**Comment by NathanWolf** [comment]
What is the output of the `/magic` command?

**Comment by NathanWolf** [comment]
Also what kind of device and version of Bedrock are you using?

**Comment by ibbotsoz** [comment]
when enter /magic  i get the following reponse 

Magic 8.0.2-52f1d8e
use /magic help for more info

im running on laptop and using 1.16.100. im pretty sure that not even my java players can craft some of the items like spell book.

**Comment by NathanWolf** [comment]
Hm, that's a shame, I really thought I had found and fixed the issue in 8.0.2. I'll take another look.

**Comment by NathanWolf** [comment]
I've gotten in touch with the Geyser devs and they seem to think it's something they'll have to look at. I've opened a ticket here you if you want to follow the progress or add any of your own experiences:

https://github.com/GeyserMC/Geyser/issues/1571

**Comment by NathanWolf** [comment]
I think I've found a workaround, please try out this dev build:

https://jenkins.elmakers.com/job/Magic-Stable/11/artifact/Magic/target/Magic-8.0.3-SNAPSHOT.jar

**Comment by ibbotsoz** [comment]
still same issue for me im afraid when using dev build

**Comment by NathanWolf** [comment]
I don't know if I can fix the new recipes, then. They seem to be working fine for me. I'll see if I can get a demo server up for you to try out, maybe it's some other plugin interaction, though I doubt it. There were definitely some real problems with Bedrock (and to a lesser degree, Java) crafting but I really think I have them all fixed.

I guess in the meantime if you want you can switch back to the old recipes with `/mconfigure example set 7` or by using the recipes file here:

https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/main/resources/examples/7/crafting.yml

Note that I can really only test on iOS, what kind of device are you using?

**Comment by NathanWolf** [comment]
Ok I think I got Geyser + Bungee working - if you want, go to `bedrock.elmakers.com`. 

If you end up on the sandbox server, there's an NPC that should send you to survival - but I'm hoping you go to survival.

You should start with some ingredients to test out crafting, if it does not work for you there please let me know.

**Comment by ibbotsoz** [comment]
im using windows 10 laptop. i will try when i get a chance and get back to you. thanks

**Comment by ibbotsoz** [comment]
it seems that the wand can be crafted by bedrock players and functions as it should as far as i can tell. spell book cannot. not sure about other items yet

**Comment by ibbotsoz** [comment]
i test on your test server and spellbook can be crafted.  is the test server running spigot geyser or bungee geyser?

**Comment by NathanWolf** [comment]
Bungee geyser

**Comment by NathanWolf** [comment]
Oh make *sure* you're totally up to date on Geyser- there was a bug on their side too that was fixed very recently.

In fact I need to update my own private server, I'll test the spellbook after I'm able to do that. That one is just Spigot/Geyser.

**Comment by NathanWolf** [comment]
Ok I got my spigot/geyser server updated, and I was able to craft the spellbook there too.

One thing to note (besides of course make sure to update Geyser), once you have a magic heart get kind of glitched out, that item may be permanently glitched out. You'd need to dispose of any like that (`/cast disposal` is helpful for that) and get new ones.

**Comment by NathanWolf** [comment]
Was this perhaps not working because you still had the old version on your server, too?
